### ISSUE TITLE
查找弹幕服务器时出错

### ISSUE THREAD

**Issue by huiyadanli** [lkeme/BiliHelper#1]
[2018-03-12 21:51:58] [BiliLogin] 加载账号密码
[2018-03-12 21:51:58] [BiliLogin] 加载成功,获取加密信息
[2018-03-12 21:51:58] [BiliLogin] 获取Cookie成功
[2018-03-12 21:51:59] [签到] 今天已签到过
[2018-03-12 21:51:59] [心跳] PCHeart: OK!
[2018-03-12 21:51:59] [心跳] level:35 exp:25568558/30000000 (85.229%)
[2018-03-12 21:51:59] [宝箱] 领取宝箱，内含 30 瓜子，需要 3 分钟开启
[2018-03-12 21:51:59] [宝箱] 等待 21:21:28 领取
[2018-03-12 21:51:59] [投喂] 开始翻动礼物
[2018-03-12 21:51:59] [收礼] 没有礼物可以领了呢
[2018-03-12 21:51:59] [扭蛋币] EggMoney:获取成功
[2018-03-12 21:52:00] [COIN] 硬币兑换: 兑换成功
[2018-03-12 21:52:00] [SOCKET] 查找弹幕服务器中
PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /home/script/BiliHelper-master/includes/Traits/socketHelper.php:93
Stack trace:
#0 /home/script/BiliHelper-master/includes/Traits/socketHelper.php(24): Bilibili->getServer(23058)
#1 /home/script/BiliHelper-master/includes/Bilibili.php(413): Bilibili->socketHelperStart()
#2 /home/script/BiliHelper-master/includes/Bilibili.php(155): Bilibili->customerAction()
#3 /home/script/BiliHelper-master/index.php(40): Bilibili->run()
#4 /home/script/BiliHelper-master/index.php(43): start(Array, 'sid=bvpnx7ms;De...', Array)
#5 {main}
  thrown in /home/script/BiliHelper-master/includes/Traits/socketHelper.php on line 93

**Comment by lkeme** [comment]
你修改过吗？重试也这样吗？还是只出现过一次？

**Comment by huiyadanli** [comment]
今天看了下 php-xml 没装，装上就可以了

**Comment by lkeme** [comment]
好的
