### ISSUE TITLE
运行到这里直接就消失了。

### ISSUE THREAD

**Issue by Dkw346456741** [lkeme/BiliHelper#34]
[2018-08-20 23:39:20] Bilibili.INFO: [dkw]开始启动程序... [] []
[2018-08-20 23:39:20] Bilibili.INFO: [dkw]正在检查令牌合法性... [] []
[2018-08-20 23:39:20] Bilibili.INFO: [dkw]令牌有效期: 2018-09-04 13:26:11 [] []
[2018-08-20 23:39:21] Bilibili.INFO: [dkw]每日礼包领取成功 [] []
[2018-08-20 23:39:21] Bilibili.INFO: [dkw]正在生成直播间信息... [] []
[2018-08-20 23:39:23] Bilibili.INFO: [dkw]直播间信息生成完毕! [] []
[2018-08-20 23:39:25] Bilibili.INFO: [dkw]WEB端 发送心跳正常! [] []
[2018-08-20 23:39:25] Bilibili.INFO: [dkw]APP端 发送心跳正常! [] []
[2018-08-20 23:39:26] Bilibili.NOTICE: [dkw]今天所有的宝箱已经领完! [] []
[2018-08-20 23:39:26] Bilibili.INFO: [dkw]正在检查每日任务... [] []
[2018-08-20 23:39:27] Bilibili.INFO: [dkw]检查任务「双端观看直播」... [] []
[2018-08-20 23:39:27] Bilibili.NOTICE: [dkw]已经领取奖励 [] []
[2018-08-20 23:39:27] Bilibili.INFO: [dkw]检查任务「每日签到」... [] []
[2018-08-20 23:39:27] Bilibili.NOTICE: [dkw]该任务已完成 [] []
[2018-08-20 23:39:28] Bilibili.INFO: [dkw][APP]银瓜子兑换硬币: 每天最多能兑换 1 个 [] []
[2018-08-20 23:39:30] Bilibili.INFO: [dkw][PC]银瓜子兑换硬币: 每天最多能兑换 1 个 [] []
[2018-08-20 23:39:31] Bilibili.NOTICE: [dkw]你没有需要签到的应援团! [] []
[2018-08-20 23:39:32] Bilibili.INFO: [dkw]没有礼物可以领了呢! [] []
[2018-08-20 23:39:45] Bilibili.INFO: [dkw]实物抽奖起始值[126]，结束值[206] [] []

**Comment by Dkw346456741** [comment]
感觉是我少了点什么  有出过同样情况的么。

**Comment by lkeme** [comment]
@Dkw346456741 什么意思？没看懂，描述清楚问题

**Comment by Dkw346456741** [comment]
emmmm   就是直接就崩了。。。screen的那一页就那么没了。

**Comment by Dkw346456741** [comment]
啊对  我不用screen  看看报什么错。。。

**Comment by Dkw346456741** [comment]
PHP Fatal error:  Uncaught Error: Class 'Wrench\Client' not found in /root/b/src/Websocket.php:45
Stack trace:
#0 /root/b/src/Websocket.php(32): lkeme\BiliHelper\Websocket::init()
#1 /root/b/index.php(63): lkeme\BiliHelper\Websocket::run()
#2 /root/b/index.php(101): lkeme\BiliHelper\Index::run('3.conf')
#3 {main}
  thrown in /root/b/src/Websocket.php on line 45

Fatal error: Uncaught Error: Class 'Wrench\Client' not found in /root/b/src/Websocket.php:45
Stack trace:
#0 /root/b/src/Websocket.php(32): lkeme\BiliHelper\Websocket::init()
#1 /root/b/index.php(63): lkeme\BiliHelper\Websocket::run()
#2 /root/b/index.php(101): lkeme\BiliHelper\Index::run('3.conf')
#3 {main}
  thrown in /root/b/src/Websocket.php on line 45

**Comment by lkeme** [comment]
缺个东西，用composer安装

**Comment by Dkw346456741** [comment]
感谢  问题出在没更新composer依赖库
